# Rollout test config
# Tests rollout support with 'default' branch for non-enrolled clients

slug: adaptive-performance-power-saving-v2
segments:
- Windows
- Linux
- Mac
histograms:
- metrics.memory_distribution.memory_total
- metrics.timing_distribution.performance_pageload_fcp
- metrics.timing_distribution.performance_pageload_load_time
- metrics.timing_distribution.perf_largest_contentful_paint
- metrics.labeled_counter.power_cpu_time_per_process_type_ms:
    aggregate: percentiles
- metrics.quantity.gfx_target_frame_rate:
    aggregate: percentiles
events:
- crash
- pageload:
    fcp_time:
      max: 30000
    lcp_time:
      max: 30000
    load_time:
      max: 30000
    response_time:
      max: 30000
